In [2]:
import pandas as pd
import numpy as np
print(pd.__version__)

3.0.3

In [3]:
s = pd.Series([10, 20, 30],
index=["a", "b", "c"],
name="ventas")

print(s)

a    10
b    20
c    30
Name: ventas, dtype: int64

In [5]:
df = pd.DataFrame({
"producto": ["A", "B"],
"unidades": [10, 20],
})
print(df)

  producto  unidades
0        A        10
1        B        20

In [3]:
s = pd.Series([120, 85, 200, 45],
index=["ene", "feb", "mar", "abr"],
name="ventas")
print(s["mar"]) # acceso por etiqueta
print("***"*100)
print(s * 1.21) # vectorizado:

200
************************************************************************************************************************************************************************************************************************************************************************************************************
ene    145.20
feb    102.85
mar    242.00
abr     54.45
Name: ventas, dtype: float64

In [ ]:
# a) Desde un diccionario de listas (la más habitual)
df = pd.DataFrame ({
      "producto" : ["Laptop", "Monitor" , "Teclado" ],
      "unidades" : [3, 7, 12],
      "precio": [1200.0, 320.0, 95.0],
})

print(df)

<bound method NDFrame.head of   producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0>

In [15]:
# b) Desde una lista de diccionarios (típico de una API JSON)
df2 = pd. DataFrame ([{"producto" : "Laptop", "unidades" : 3},
{"producto" : "Monitor" , "unidades" : 7}])
print(df2)

  producto  unidades
0   Laptop         3
1  Monitor         7

In [16]:
# c) Desde una lista de listas, indicando las columnas
df3 = pd. DataFrame ([["Laptop", 3], ["Monitor" , 7]],
columns=[ "producto" , "unidades" ])
print(df3)

  producto  unidades
0   Laptop         3
1  Monitor         7

In [4]:
# d) Desde un array de NumPy
df4 = pd. DataFrame (np.random.rand(3, 2), columns=[ "x", "y"])
print(df4)

          x         y
0  0.382380  0.963725
1  0.233312  0.686561
2  0.664415  0.799261

In [23]:
df = pd.DataFrame ({
      "producto" : ["Laptop", "Monitor" , "Teclado" ],
      "unidades" : [3, 7, 12],
      "precio": [1200.0, 320.0, 95.0],
})
print(df)
print("*"*100)
df["importe" ] = df["unidades" ] * df["precio"]
print(df.shape)
print("*"*100)
print(df.columns.tolist())
print("*"*100)
print(df)

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0
****************************************************************************************************
(3, 4)
****************************************************************************************************
['producto', 'unidades', 'precio', 'importe']
****************************************************************************************************
  producto  unidades  precio  importe
0   Laptop         3  1200.0   3600.0
1  Monitor         7   320.0   2240.0
2  Teclado        12    95.0   1140.0

In [ ]:
ventas = pd.read_csv("C:/Users/diego/Documents/primer_python/01-python-intro/data/ventas.csv",
parse_dates=["fecha"])
ventas.head(3)
ventas.shape
ventas.info()
ventas.describe()
ventas.sample(5, random_state=1)

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   datetime64[us]
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(2), str(4)
memory usage: 75.1 KB

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
636,2024-07-15,Norte,Pedro Diaz,Escritorio,Mobiliario,9,450,0.00
683,2024-07-28,Centro,Carlos Vega,Raton Ergo,Accesorios,7,45,0.15
1033,2024-11-07,Sur,Sofia Leon,Silla Ergo,Mobiliario,3,280,0.10
190,2024-02-25,Oeste,Luis Gomez,Tablet Air,Tecnologia,13,640,0.00
1083,2024-11-27,Sur,Sofia Leon,Tablet Air,Tecnologia,8,640,0.00

In [6]:
import pandas as pd

# Crea una Series con las temperaturas [21, 24, 19, 27, 30] e índice de lunes a viernes.
temperaturas = pd.Series(
    [21, 24, 19, 27, 30],
    index=["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"]
)

print(temperaturas)

# Muestra la media, el máximo y el día que corresponde al máximo (usa .idxmax()).
print("=" * 100)
print("Media: ", temperaturas.mean())
print("Máximo: ", temperaturas.max())
print("Día máximo: ", temperaturas.idxmax())
print("Día máximo índice: ", temperaturas.argmax())
print("=" * 100)

# Crea un DataFrame con 5 productos: nombre, categoría, stock y precio (inventados).
df = pd.DataFrame(
    {
        "nombre": ["Laptop", "Monitor", "Teclado", "Mouse", "Fuente de poder"],
        "categoria": ["Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología"],
        "stock": [3, 7, 12, 1, 0],
        "precio": [1200.0, 320.0, 95.0, 12.23, 90.8]
    }
)

df.head()

# Añade una columna valor_stock = stock × precio.
df["valor_stock"] = df["stock"] * df["precio"]

df.head()

# Imprime la forma del DataFrame y la lista de nombres de columna.
print(df.shape)

print(df.columns.to_list())

Lunes        21
Martes       24
Miércoles    19
Jueves       27
Viernes      30
dtype: int64
====================================================================================================
Media:  24.2
Máximo:  30
Día máximo:  Viernes
Día máximo índice:  4
====================================================================================================
(5, 5)
['nombre', 'categoria', 'stock', 'precio', 'valor_stock']

In [ ]:
df = pd.read_csv(
    "C:/Users/diego/Documents/primer_python/01-python-intro/data/ventas.csv"
    

)
df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [13]:
df.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 75.1 KB

In [15]:
df.describe()

          unidades  precio_unitario    descuento
count  1200.000000      1200.000000  1165.000000
mean      7.275833       387.412500     0.047639
std       4.054024       346.020316     0.056273
min       1.000000        45.000000     0.000000
25%       4.000000       130.000000     0.000000
50%       7.000000       280.000000     0.000000
75%      11.000000       450.000000     0.100000
max      14.000000      1200.000000     0.150000

In [16]:
df["unidades"].max()

np.int64(14)

In [18]:
df.sample(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
287,2024-03-30,Centro,Carlos Vega,Auriculares,Accesorios,8,130,0.05
888,2024-09-29,Oeste,Pedro Diaz,Auriculares,Accesorios,12,130,0.00
706,2024-08-05,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.05
763,2024-08-22,Norte,Luis Gomez,Tablet Air,Tecnologia,3,640,0.05
173,2024-02-21,Norte,Javier Sanz,Teclado Mec,Accesorios,8,95,0.00
1129,2024-12-09,Sur,Ana Torres,Auriculares,Accesorios,7,130,0.00
964,2024-10-20,Oeste,Elena Mora,Monitor 27,Tecnologia,3,320,0.00
1090,2024-11-30,Sur,Javier Sanz,Tablet Air,Tecnologia,8,640,0.00
253,2024-03-14,Norte,Javier Sanz,Escritorio,Mobiliario,8,450,0.00
812,2024-09-07,Norte,Ana Torres,Escritorio,Mobiliario,13,450,0.15

In [19]:
df.describe(include="object")

C:\Users\diego\AppData\Local\Temp\ipykernel_33616\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

             fecha region    vendedor    producto   categoria
count         1200   1200        1182        1200        1200
unique         349      5           8           8           3
top     2024-02-21  Norte  Marta Ruiz  Silla Ergo  Tecnologia
freq             9    305         170         177         447

In [20]:
df["region"].unique()

<StringArray>
['Oeste', 'Sur', 'Centro', 'Norte', 'Este']
Length: 5, dtype: str

In [23]:
df['region'].nunique()

5

In [24]:
df["producto"].value_counts()

producto
Silla Ergo     177
Monitor 27     159
Auriculares    158
Tablet Air     149
Raton Ergo     146
Laptop Pro     139
Escritorio     139
Teclado Mec    133
Name: count, dtype: int64

In [25]:
df["producto"].mode()

0    Silla Ergo
Name: producto, dtype: str

In [27]:
###Selecionar columnas
df[["fecha","producto"]]

           fecha     producto
0     2024-01-02  Auriculares
1     2024-01-02   Monitor 27
2     2024-01-02   Silla Ergo
3     2024-01-02   Laptop Pro
4     2024-01-03  Auriculares
...          ...          ...
1195  2024-12-30   Raton Ergo
1196  2024-12-30   Laptop Pro
1197  2024-12-31   Monitor 27
1198  2024-12-31   Monitor 27
1199  2024-12-31   Raton Ergo

[1200 rows x 2 columns]

In [29]:
df.loc[0:4]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1

In [30]:
df.loc[0:2,["producto","unidades"]]

      producto  unidades
0  Auriculares         5
1   Monitor 27        14
2   Silla Ergo         1

In [33]:
df.iloc[-1]

fecha              2024-12-31
region                  Norte
vendedor           Marta Ruiz
producto           Raton Ergo
categoria          Accesorios
unidades                    8
precio_unitario            45
descuento                 0.0
Name: 1199, dtype: object

In [34]:
df.iloc[-5:,1]

1195     Este
1196     Este
1197    Oeste
1198    Norte
1199    Norte
Name: region, dtype: str

In [35]:
#ordenar dataframe
df.sort_values("unidades", ascending= False)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
420,2024-05-14,Este,Javier Sanz,Monitor 27,Tecnologia,14,320,0.10
309,2024-04-07,Norte,Elena Mora,Tablet Air,Tecnologia,14,640,0.05
607,2024-07-07,Centro,Javier Sanz,Auriculares,Accesorios,14,130,0.05
604,2024-07-05,Sur,Elena Mora,Laptop Pro,Tecnologia,14,1200,0.00
601,2024-07-05,Sur,Pedro Diaz,Monitor 27,Tecnologia,14,320,0.05
...,...,...,...,...,...,...,...,...
447,2024-05-23,Oeste,Marta Ruiz,Silla Ergo,Mobiliario,1,280,0.00
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
407,2024-05-06,Este,Elena Mora,Laptop Pro,Tecnologia,1,1200,0.05
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00

In [36]:
df.sort_values(["unidades", "region"], ascending= [False,True])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.00
83,2024-01-30,Centro,Elena Mora,Auriculares,Accesorios,14,130,0.10
162,2024-02-19,Centro,Elena Mora,Monitor 27,Tecnologia,14,320,0.15
391,2024-04-30,Centro,Carlos Vega,Silla Ergo,Mobiliario,14,280,0.00
446,2024-05-23,Centro,Luis Gomez,Raton Ergo,Accesorios,14,45,0.05
...,...,...,...,...,...,...,...,...
1044,2024-11-09,Sur,Sofia Leon,Teclado Mec,Accesorios,1,95,0.10
1079,2024-11-26,Sur,Elena Mora,Tablet Air,Tecnologia,1,640,0.15
1094,2024-12-01,Sur,Marta Ruiz,Silla Ergo,Mobiliario,1,280,0.00
1104,2024-12-03,Sur,Pedro Diaz,Monitor 27,Tecnologia,1,320,0.05
1126,2024-12-08,Sur,Pedro Diaz,Escritorio,Mobiliario,1,450,0.00

In [40]:
df.sort_values("unidades", ascending= False).iloc[0:3]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
420,2024-05-14,Este,Javier Sanz,Monitor 27,Tecnologia,14,320,0.10
309,2024-04-07,Norte,Elena Mora,Tablet Air,Tecnologia,14,640,0.05
607,2024-07-07,Centro,Javier Sanz,Auriculares,Accesorios,14,130,0.05

In [41]:
df.head()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1